name: mido
on:
  workflow_dispatch:

jobs:
  teletubiesbuild:
    runs-on: ubuntu-latest

    steps:
    - name: Creating Env!
      uses: actions/checkout@v2

    - name: Setting up Env!
      run: |
          git clone https://github.com/akhilnarang/scripts x
          cd x/setup && bash android_build_env.sh
    - name: Building Kernel..
      run: |
          chmod +x build.sh && build mido.sh
      shell: bash
      env:
         TZ: Asia/Jakarta
         CHATID: ${{ secrets.CHAT_ID }}
         API_BOT: ${{ secrets.BOT_API }}
